[feat] 도감 조회, 도감 교환 서비스로직 개발
lets-ONION/ONION-Server pull request #12
Opened 2024-07-29 10:00 UTC by Chaeyoung714

### 이슈 번호
- 
### 작업한 내용
-도감 조회, 도감 교환 서비스로직 개발

### 남은 작업
- 도감 dto, controller 개발
- 양파 일기 검증 로직 api 개발

아직 계속 수정중이므로, 실수가 있거나 리뷰 있다면 코멘트 부탁드리겠습니당

2024-07-29 11:29 UTC, ShinSub98 requested changes
수고하셨습니다!
확인 부탁드립니다!

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/Onion.java
> +    @Id @GeneratedValue
mysql pk 생성 전략 기본값이 IDENTITY긴 한데 가끔 SEQUENCE로 충돌날 때가 있어서
`@GeneratedValue(strategy = GenerationType.IDENTITY)`로 정의해두는 게 안전할 것 같아요

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/Onion.java
> +@Getter
`@NoArgsConstructor(access = AccessLevel.PROTECTED)`
기본 생성자 만들고 접근수준 제어하는 롬복 어노테이션인데 미리 추가해두면 앞으로 개발할 때 안전할 것 같습니다

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/Onion.java
> +    public void decreaseQuantity(int quantity) {
이번 서비스에서 양파 양은 한 번에 하나씩만 늘어나고 줄어들 테니까 quantity 파라미터를 없애고
```java
if (collectedQuantity > 0) {collectedQuantity--;}
```
는 어떨까요?

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/Onion.java
> +            throw new NotEnoughQuantityException("더이상 삭제할 수 없습니다.");
util/exception에 Exceptions라고 예외 처리 가능한 enum 클래스 만들어뒀는데
```java
throw new CustomException(Exceptions.[직접 정의한 예외]);
```
로 처리해두시면 자동으로 ResponseEntity<ExceptionDTO>로 래핑되어 응답 나가도록 해뒀습니다!

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/OnionBook.java
> +    @OneToOne(fetch = LAZY)
양파도감 -> 유저보다 유저 -> 양파도감으로 조회하는 경우가 많을 것 같으니
관계의 주인을 유저로 두고 양파 도감쪽에 `mappedBy` 옵션을 둘까요?
이 부분은 저도 Member 엔티티에 양파도감 필드를 추가해야 하니 다시 얘기해봐야 할 것 같습니다

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/OnionBook.java
> +    @JoinColumn(name = "onion_ggang")
양파 기록 테이블도 없어지고, 양파 클래스에 들어갈 필드도 특별히 없으니 양파 클래스를 엔티티가 아니라 `@Embedded`클래스로 두는 건 어떨까요?

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/trade/TradeRequest.java
> +    private LocalDate requestAt;
혹시 모르니 시각도 같이 저장할 수 있는 LocalDateTime을 사용하는 것도 좋을 것 같습니다.
또 클래스에 `@EntityListeners(AuditingEntityListener.class)` 어노테이션을 추가하고
requestAt 필드에 `@CreatedDate` 어노테이션을 추가하면 엔티티가 생성된 순간 JPA가 자동으로 해당 필드를 추가해줘서 편리합니다. (django의 `auto_add_now`랑 비슷합니다)

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/trade/TradeRequest.java
> +    public static TradeRequest createTradeRequest(Member fromMember, Member toMember, OnionType fromOnionType, OnionType toOnionType) {
안전하게 생성자 메소드로 선언하고 롬복의 `@Builder` 어노테이션을 사용하는 건 어떨까요? 불필요한 데이터 변경을 사전에 방지할 수 있습니다

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/domain/trade/TradeStatus.java
> +    PENDING, ACCEPT, REFUSE, CANCEL
저는 친구 거절을 REJECT로 설정했는데 저희 둘이 얘기해서 하나로 맞추는 게 좋을 것 같아요! CANCEL은 저도 친구 요청에 추가하겠습니다

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionBookRepository.java
> +public interface OnionBookRepository {
`extends JpaRepository<OnionBook, Long>`으로 JpaRepository도 활용하면 좋을 것 같습니다

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionBookRepositoryImpl.java
> +    public OnionBook findById(Long id) { //Onion 객체들까지 다 불러오는지 봐야함
Onion 객체들까지 다 불러오려면 `createQuery()` 메소드로 left join fetch 조회해야 합니다!

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionRepository.java
> +public interface OnionRepository {
마찬가지로 JpaRepository 상속받아서 쓰면 편리할 것 같습니다.

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionRepositoryImpl.java
> +    }
JPQL 쿼리문으로 잘 이해가 안 됐는데 memberId와 OnionType이 일치하는 Onion 엔티티를 찾는 코드일까요?? 그럼
```java
return em.createQuery("select o from Onion o"
	 + " left join fetch o.member"
	 + " where o.member.id =:memberId"
	 + " and o.onionType =:onionType",
	 Onion.class)
	 .setParameter("memberId", memberId)
	 .setParameter("onionType", onionType)
	 .getSingleResult();
```
로 하셔야 할 거예요!
저도 에디터에서 쓴 게 아니고 그냥 마크다운으로 쓴 거라 맞을지는 모르겠습니다ㅜ

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionRepositoryImpl.java
> +    }
만약 Onion 엔티티를 `@Embeddable` 클래스로 만들면 OnionBook 클래스만 조회해도 될 것 같아요

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/trade/TradeRepositoryImpl.java
> +    }
여기도 Member가 지연 로딩으로 매핑될 테니까
```java
return em.createQuery("select t from TradeRequest t"
	 + " left fetch join t.fromMember fm"
	 + " where fm.id =:memberId",
	 TradeRequest.class)
	 .setParameter("memberId", memberId)
	 .getResultList();
```
가 좋을 것 같아요

그리고 중요한 건 아닌데 스프링 메소드 작명 컨벤션이 리스트를 리턴할 때는 보통 "findAllByFromMemberId"로 지어서 이런 식으로 맞추는 것도 좋을 것 같아요

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/repository/trade/TradeRepositoryImpl.java
> +    }
JpaRepository를 상속하면 JpaRepository에서 제공하는 save() 메소드를 사용할 수 있습니다!
EntityManager의 메소드들은 저수준 메소드들이라 비슷한 메소드들도 사용법이 나뉘어져 있는데 JpaRepository의 save() 메소드는 직접 그런 부분을 핸들링해줘서 안전하게 사용할 수 있습니다.

2024-07-29 11:29 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/service/onionBook/OnionBookServiceImpl.java
> +    public OnionBook findByMemberId(Long memberId) {
저희 응답 컨벤션 노션에 적어뒀었는데 확인 한 번 부탁드립니다!
[링크](https://www.notion.so/API-6f8f33b7df51461582f89b7cb4f0e107?pvs=4#03ddb53c2e2c41c28a0b2b7804aa8268)

ResponseDTO랑 Responses라는 enum 클래스 만들어뒀는데
```java
return new ResponseDTO<>("응답 데이터", Responses.OK);
```
이렇게 리턴해주시면 자동으로 컨트롤러에서 리턴해줄 때 스프링에서 중간에 가로채서
`ResponseEntity<ResponseDTO<T>>`로 래핑해서 응답하도록 설정해뒀습니다! 필요하신 응답에 따라서 `Responses.CREATED`처럼 골라서 넣어주시면 됩니다.

2024-07-29 16:08 UTC, Chaeyoung714 commented
> 수고하셨습니다! 확인 부탁드립니다!

매우매우 감사드립니다... 하나씩 참고하면서 변경하면서 궁금한 거 있으면 연락드리겠습니당

2024-07-29 16:09 UTC, Chaeyoung714 commented on src/main/java/site/lets_onion/lets_onionApp/domain/trade/TradeStatus.java
> +    PENDING, ACCEPT, REFUSE, CANCEL
넵 그럼 pending, accept, reject, cancel로 맞추겠습니당

2024-07-31 07:01 UTC, Chaeyoung714 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/Onion.java
> +@Getter
앗 근데 이거 설정하면 Onion()으로는 생성이 막히고 따로 생성메서드를 추가해야하는 걸로 알고 있는데, 오빠가 멤버 생성 시점에서 Onion 객체 생성해두게 설정했나요?? 아니면 제쪽에서 따로 메서드 추가를 해야하나욤

2024-07-31 07:12 UTC, Chaeyoung714 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/OnionBook.java
> +    @OneToOne(fetch = LAZY)
넵

`@OneToOne(mappedBy = "onionBook", fetch = LAZY)
  private Member member;`

다음과같이 추가해뒀으니 Member에 onionBook 필드 추가하면 좋을 것 같습니당

2024-07-31 08:02 UTC, Chaeyoung714 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionRepositoryImpl.java
> +    }
앗 ERD 보시면 Onion 엔티티에 member이 안들어가여! 그래서 memberId에 맞는 OnionBook 엔티티의 필드를 보면서, 내가 원하는 onionType에 맞는 필드를 꺼내야하는 건데... jpql로 짜자니 어렵네여...ㅎ

2024-08-01 17:43 UTC, Zena0128 reviewed
고생하셨슴다! 리뷰 세개만 확인 부탁드림다

2024-08-01 17:43 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/domain/onionBook/OnionBook.java
> +                throw new IllegalArgumentException("Unknown OnionType");
바로 내장 Exception을 발생시키면 500 서버에러가 뜰 수 있다고 해여..! customexception으로 리턴하는 것이 어떠한지용

2024-08-01 17:43 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionBookRepositoryImpl.java
> +    public OnionBook save(OnionBook onionBook) {
onionBookRepisitory, JpaRepository extend한 repository의 save메소드 사용하지 않고 직접 save 메소드를 override한 이유가 있나요?-?

2024-08-01 17:43 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/dto/trade/TradeRequestDTO.java
> +    @JsonCreator
이거 없어도 잘 작동하지 않나요?! 없으면 에러나나여??

2024-08-01 18:01 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/dto/trade/TradeRequestDTO.java
> +    @JsonCreator
아ㅏ 역직렬화 필요한 DTO라 붙였구나
https://effortguy.tistory.com/465 요 글 읽고 저는 @NoArgsConstructor 붙이니까 역직렬화 잘 돼서 JsonCreator 말고 저걸로 하긴 했는데 원래는 JsonCreator를 사용한다고 하네용... 제가 조금 더 공부해보겠읍니당

2024-08-01 18:02 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/dto/trade/TradeRequestDTO.java
> +    @JsonCreator
https://mingyum119.tistory.com/308 나중에 제가 참고할 용으로.. 공부자료 하나 남겨놓고가께용,,

2024-08-02 08:21 UTC, Chaeyoung714 commented on src/main/java/site/lets_onion/lets_onionApp/repository/onionBook/OnionBookRepositoryImpl.java
> +    public OnionBook save(OnionBook onionBook) {
엇 아뇨 모르고있었는데 정섭오빠도 알려줬었는데 제가 반영하는 걸 까먹었네요.. 일단 서버 완성되고 나서 리팩토링 해보겟숩니다

2024-08-02 11:31 UTC, ShinSub98 approved these changes
수고하셨습니다!

2024-08-02 11:43 UTC, merged