[Feat] 푸시 알림 및 유저 카카오 동의/친구 데이터 조회 기능 추가
lets-ONION/ONION-Server pull request #8
Opened 2024-07-26 08:28 UTC by ShinSub98

### 이슈 번호
- #3 #5 #7 
### 작업한 내용
- 푸시 알림 기능 추가
- 유저의 카카오 계정 정보 동의 현황 확인 API 추가
- 유저의 카카오 친구 리스트 조회 API 추가
- Redis 템플릿 추가 : 카카오 토큰 저장용
- 기타 리팩토링

2024-07-26 09:25 UTC, Zena0128 requested changes
확인 완료했습니다! 몇가지만 확인 부탁드립니다용

2024-07-26 09:25 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/service/member/MemberServiceImpl.java
> +                new NullPointerException("User Not Exists"));
NullPointerException보다 UserNotFoundException같은 커스텀 예외를 만들어서 발생시키는 것은 어떠할지요??

2024-07-26 09:25 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/util/exception/Exceptions.java
>      KAKAO_AUTH_FAILED_WITH_TOKEN(401, "Kakao Auth Failed With Toekn"),
token 오타나쓰요

2024-07-26 09:25 UTC, Zena0128 commented on src/main/java/site/lets_onion/lets_onionApp/util/push/PushType.java
> +
기능 명세서에 따르면 푸시 알림이 
1. 양파 교환 요청 받음
2. 양파 교환 요청 수락됨
3. 친구 요청 받음
4. 친구 요청 수락됨
5. 유저가 설정한 특정 시간까지 그날의 물주기 수행 안 했을 시 리마인드

요렇게 다섯가지라 2, 4, 5에 해당하는 enum 더 추가해야 할 것 같슴다

2024-07-26 09:30 UTC, ShinSub98 commented on src/main/java/site/lets_onion/lets_onionApp/service/member/MemberServiceImpl.java
> +                new NullPointerException("User Not Exists"));
맞네요 생각해보니 이미 MemberNotExist 만들어놨는데 NullPoint 넣어버렸네요

2024-07-27 07:58 UTC, Chaeyoung714 reviewed
고생하셨습니다!

2024-07-27 07:58 UTC, Chaeyoung714 commented on src/main/java/site/lets_onion/lets_onionApp/service/member/MemberServiceImpl.java
> +        serviceRedisConnector.setWithTtl(memberId.toString(), message, 86400000L); // 24시간 유지
단톡에도 올렸는데, 저희 서비스 로직상 상태메세지 갱신 가능한 시간이 이전 상태메세지 작성 24시간 이후인건지 매일 자정인건지 궁금합니당

2024-07-27 09:21 UTC, Chaeyoung714 approved these changes
확인했습니다

2024-07-27 09:47 UTC, merged